# Generated by Django 3.1.1 on 2020-09-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyuserpoints',
            name='points_accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loyaltyuserpoints',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
