# Generated by Django 3.1.1 on 2020-09-03 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0002_auto_20200903_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltyprogramtransactions',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
