# Generated by Django 3.1.1 on 2020-09-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_loyaltyuserpoints_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
