# Generated by Django 3.1.1 on 2020-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_auto_20200903_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogramtransactions',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
