# Generated by Django 3.1.1 on 2020-09-22 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty', '0006_auto_20200903_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyuserpoints',
            name='related_user',
        ),
        migrations.AlterField(
            model_name='loyaltyprogramtransactions',
            name='related_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_related_transactions', to='loyalty.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogramtransactions',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_user', to='loyalty.loyaltyuserpoints'),
        ),
        migrations.CreateModel(
            name='LoyaltyTenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=250)),
                ('tenant_description', models.CharField(max_length=250)),
                ('tenant_contact', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('related_user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgramSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('card_number', models.CharField(max_length=250)),
                ('date_suspended', models.DateTimeField()),
                ('date_unsubscribed', models.DateTimeField()),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('related_loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_related', to='loyalty.loyaltyprogram')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='related_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tenant', to='loyalty.loyaltytenants'),
        ),
        migrations.AddField(
            model_name='loyaltyuserpoints',
            name='related_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_loyalty_subscriptions', to='loyalty.loyaltyprogramsubscriptions'),
        ),
    ]
