# Generated by Django 3.1.1 on 2020-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_auto_20200922_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogramsubscriptions',
            name='date_suspended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyprogramsubscriptions',
            name='date_unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
