# Generated by Django 3.1.1 on 2020-09-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_auto_20200922_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogramsubscriptions',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='loyaltyprogramsubscriptions',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
