# Generated by Django 3.1.1 on 2020-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_auto_20201118_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
