# Generated by Django 3.1.1 on 2020-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_loyaltyprogram_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogrambranches',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
