# Generated by Django 3.1.1 on 2021-01-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('nin_number', models.CharField(max_length=250)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=250)),
                ('client_email', models.CharField(max_length=250)),
                ('order_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('crypto_type', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('CELO', 'CELO'), ('XRP', 'XRP'), ('LTC', 'LTC')], max_length=10)),
                ('fiat_type', models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD')], default='UGX', max_length=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_status', models.CharField(choices=[('UNFULFILLED', 'UNFULFILLED'), ('FULFILLED', 'FULFILLED'), ('DECLINED', 'DECLINED')], default='UNFULFILLED', max_length=15)),
                ('crypto_unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('completed_by', models.CharField(blank=True, max_length=250, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message', models.TextField()),
                ('status', models.CharField(choices=[('UNDELIVERED', 'UNDELIVERED'), ('DELIVERED', 'DELIVERED')], default='UNDELIVERED', max_length=15)),
                ('date_dispatched', models.DateTimeField(auto_now_add=True)),
                ('related_order_telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_related_telegram', to='binusu.orders')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.CharField(max_length=250)),
                ('client_email', models.CharField(max_length=250)),
                ('email_message', models.TextField()),
                ('status', models.CharField(choices=[('UNDELIVERED', 'UNDELIVERED'), ('DELIVERED', 'DELIVERED')], default='UNDELIVERED', max_length=15)),
                ('date_dispatched', models.DateTimeField(auto_now_add=True)),
                ('related_order_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_related_email', to='binusu.orders')),
            ],
        ),
    ]
