# Generated by Django 3.1.1 on 2021-01-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='client_email',
        ),
        migrations.AddField(
            model_name='orders',
            name='related_kyc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_kyc', to='binusu.kyc'),
            preserve_default=False,
        ),
    ]
