# Generated by Django 3.1.1 on 2021-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0003_auto_20210113_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie_photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
    ]
