# Generated by Django 3.1.1 on 2021-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0004_auto_20210113_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_amount_crypto',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
