# Generated by Django 3.1.1 on 2021-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0007_passwordresets_reset_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
