# Generated by Django 3.1.1 on 2021-02-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0008_orders_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('CELO', 'CELO'), ('XRP', 'XRP'), ('LTC', 'LTC'), ('cUSD', 'cUSD')], max_length=10),
        ),
    ]
