# Generated by Django 3.1.3 on 2021-02-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0009_auto_20210202_1338'),
        ('binusu', '0009_auto_20210202_1337'),
    ]

    operations = [
    ]
