# Generated by Django 3.1.1 on 2021-02-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0010_auto_20210209_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('account_status', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='fullfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_fullfiller', to='binusu.accountuser'),
        ),
    ]
