# Generated by Django 3.1.1 on 2021-02-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0011_auto_20210209_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogins',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logins', to='binusu.accountuser'),
        ),
        migrations.AlterField(
            model_name='userrefreshotp',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refresh_otps', to='binusu.accountuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
