# Generated by Django 3.1.3 on 2021-02-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0010_merge_20210204_0910'),
        ('binusu', '0012_auto_20210209_0904'),
    ]

    operations = [
    ]
