# Generated by Django 3.1.1 on 2021-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0012_auto_20210209_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_amount_crypto',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
