# Generated by Django 3.1.1 on 2021-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0013_auto_20210213_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('CELO', 'CELO'), ('XRP', 'XRP'), ('LTC', 'LTC'), ('cUSD', 'cUSD'), ('BCH', 'BCH')], max_length=10),
        ),
    ]
