# Generated by Django 3.1.3 on 2021-02-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0013_merge_20210209_1028'),
        ('binusu', '0013_auto_20210213_1141'),
    ]

    operations = [
    ]
