# Generated by Django 3.1.1 on 2021-02-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0014_auto_20210223_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='crypto_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_payable_amount_fiat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='warning',
            field=models.IntegerField(default=0),
        ),
    ]
