# Generated by Django 3.1.1 on 2021-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0015_auto_20210223_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='crypto_fees_type',
            field=models.CharField(blank=True, choices=[('SLOW', 'SLOW'), ('MEDIUM', 'MEDIUM'), ('FAST', 'FAST')], max_length=6, null=True),
        ),
    ]
