# Generated by Django 3.1.3 on 2021-02-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0014_merge_20210213_1146'),
        ('binusu', '0015_auto_20210223_0926'),
    ]

    operations = [
    ]
