# Generated by Django 3.1.1 on 2021-08-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0016_orders_crypto_fees_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompletions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice_number', models.CharField(max_length=8)),
                ('pay_id', models.CharField(max_length=250)),
                ('completion_status', models.BooleanField(default=False)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('disbursement_status', models.BooleanField(default=False)),
                ('time_disbursed', models.DateTimeField(blank=True, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='binusu.orders')),
            ],
        ),
    ]
