# Generated by Django 3.1.3 on 2021-05-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0016_merge_20210224_0427'),
        ('binusu', '0016_orders_crypto_fees_type'),
    ]

    operations = [
    ]
