# Generated by Django 3.1.1 on 2021-09-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0017_ordercompletions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercompletions',
            name='amount_received',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordercompletions',
            name='bnu_txid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordercompletions',
            name='bnu_unvaulted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordercompletions',
            name='callback_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordercompletions',
            name='network_confirmations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercompletions',
            name='network_txid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
