# Generated by Django 3.1.3 on 2021-09-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0017_ordercompletions'),
        ('binusu', '0017_merge_20210510_2043'),
    ]

    operations = [
    ]
