# Generated by Django 3.1.1 on 2022-04-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0018_auto_20210923_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='external_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('CELO', 'CELO'), ('XRP', 'XRP'), ('LTC', 'LTC'), ('cUSD', 'cUSD'), ('BCH', 'BCH'), ('MYST', 'MYST'), ('LINK', 'LINK'), ('USDT', 'USDT'), ('SEA', 'SEA'), ('BNB', 'BNB')], max_length=10),
        ),
    ]
