# Generated by Django 3.1.3 on 2021-09-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0018_auto_20210923_0248'),
        ('binusu', '0018_merge_20210901_1008'),
    ]

    operations = [
    ]
