# Generated by Django 3.1.1 on 2022-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0019_auto_20220426_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='external_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
    ]
