# Generated by Django 3.1.3 on 2022-04-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0019_merge_20210923_0323'),
        ('binusu', '0019_auto_20220426_0513'),
    ]

    operations = [
    ]
