# Generated by Django 3.1.1 on 2022-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binusu', '0020_auto_20220426_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercompletions',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
