# Generated by Django 3.1.1 on 2020-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
